name: heat-vulnerability
channels:
  - conda-forge
dependencies:
  - python=3.*
  - ipython=7.10.*
  - jupyterlab=3.*
  - numpy
  - pandas
  - geopandas
  - geojson
  - matplotlib
  - folium
  - rasterio
  - rasterstats
  - contextily
  - mapclassify